Project02BurgerMenu/Areas/Admin/Controllers/AdminLayoutController.cs
using Project02BurgerMenu.Content;
using Project02BurgerMenu.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project02BurgerMenu.Areas.Admin.Controllers
{

    public class AdminLayoutController : Controller
    {
        BurgerMenu01Context context = new BurgerMenu01Context();
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {

            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }
        [HttpGet]
        public PartialViewResult PartialCategoryAdd()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult PartialCategoryAdd(Category category)
        {
            context.Categories.Add(category);
            context.SaveChanges();
            return PartialView();
        }
    }
}

Project02BurgerMenu/Controllers/LoginController.cs
using Project02BurgerMenu.Content;
using Project02BurgerMenu.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Project02BurgerMenu.Controllers
{
    public class LoginController : Controller
    {
        BurgerMenu01Context db = new BurgerMenu01Context();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Admin user)
        {
            var userInfo = db.Admins.FirstOrDefault(x => x.Username == user.Username && x.Password == user.Password);
            if (userInfo != null)
            {
                FormsAuthentication.SetAuthCookie(userInfo.Username, false);
                Session["x"] = userInfo.Username.ToString();
                return RedirectToAction("ProductList", "Product", new { area = "Admin" });
            }
            else
            {
                return View();
            }
        }
    }
}

Project02BurgerMenu/Areas/Admin/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead", "AdminLayout", "Admin")

<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        @Html.Action("PartialNavbar", "AdminLayout", "Admin")
        @*@Html.Action("PartialCategoryAdd", "AdminLayout", "Admin")*@
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">

            <!-- partial:../../partials/_sidebar.html -->
            @Html.Action("PartialSidebar", "AdminLayout", "Admin")
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">

                        @RenderBody()

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard templates</a> from Bootstrapdash.com</span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="~/regal/regal/vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/regal/regal/js/off-canvas.js"></script>
    <script src="~/regal/regal/js/hoverable-collapse.js"></script>
    <script src="~/regal/regal/js/template.js"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->
</body>

</html>

Project02BurgerMenu/Areas/Admin/Views/AdminLayout/PartialCategoryAdd.cshtml
@model List<Project02BurgerMenu.Entities.Category>

<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="categoryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12 p-5">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <small>Cancel</small><span aria-hidden="true">&times;</span>
                        </button>
                        <h1 class="mb-4">Add a Category</h1>
                        <form method="post" action="@Url.Action("PartialCategoryAdd", "AdminLayout", new { area = "Admin" })">
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="m_fname">Category Name</label>
                                    <input type="text" name="CategoryName" class="form-control" id="m_fname">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3 text-center form-group">
                                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Add">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.7.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#categoryModal form').on('submit', function (event) {
            event.preventDefault(); // Prevent default form submission
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'), // Get action URL
                data: $(this).serialize(), // Serialize form data
                success: function (result) {
                    // Handle success response (e.g., show success message, close modal)
                    $('#categoryModal').modal('hide');
                    $('body').removeClass('modal-open');
                    $('.modal-backdrop').remove();
                },
                error: function (xhr, status, error) {
                    // Handle error response (e.g., show error message)
                }
            });
        });
    });
</script>

Project02BurgerMenu/Areas/Admin/Views/AdminLayout/PartialHead.cshtml
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Regal Admin</title>
    <!-- base:css -->
    <link rel="stylesheet" href="~/regal/regal/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/regal/regal/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/regal/regal/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/regal/regal/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/regal/regal/images/favicon.png" />
</head>

Project02BurgerMenu/Areas/Admin/Views/AdminLayout/PartialNavbar.cshtml
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="~/regal/regal/index.html"><img src="~/regal/regal/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="~/regal/regal/index.html"><img src="~/regal/regal/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav mr-lg-2">
            <li class="nav-item nav-search d-none d-lg-block">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="search">
                            <i class="icon-search"></i>
                        </span>
                    </div>
                    <input type="text" class="form-control" placeholder="Enter search terms..." aria-label="search" aria-describedby="search">
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-lg-flex d-none">
                <button type="button" class="btn btn-info font-weight-bold">+ Create New Reservation</button>
            </li>
            <li class="nav-item dropdown d-flex">
                <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
                    <i class="icon-air-play mx-0"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/regal/regal/images/faces/face4.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                David Grey
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                The meeting is cancelled
                            </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/regal/regal/images/faces/face2.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                Tim Cook
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                New product launch
                            </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/regal/regal/images/faces/face3.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                Johnson
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                Upcoming board meeting
                            </p>
                        </div>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown d-flex mr-4 ">
                <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="icon-cog"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Settings</p>
                    <a class="dropdown-item preview-item">
                        <i class="icon-head"></i> Profile
                    </a>
                    <a class="dropdown-item preview-item">
                        <i class="icon-inbox"></i> Logout
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown mr-4 d-lg-flex d-none">
                <a class="nav-link count-indicator d-flex align-items-center justify-content-center" href="#">
                    <i class="icon-grid"></i>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="~/regal/regal/index.html"><img src="~/regal/regal/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="~/regal/regal/index.html"><img src="~/regal/regal/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav mr-lg-2">
            <li class="nav-item nav-search d-none d-lg-block">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="search">
                            <i class="icon-search"></i>
                        </span>
                    </div>
                    <input type="text" class="form-control" placeholder="Enter search terms..." aria-label="search" aria-describedby="search">
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-lg-flex d-none">
                <button type="button" class="btn btn-info font-weight-bold">+ Create New Reservation</button>
            </li>
            <li class="nav-item dropdown d-flex">
                <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
                    <i class="icon-air-play mx-0"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/regal/regal/images/faces/face4.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                David Grey
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                The meeting is cancelled
                            </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/regal/regal/images/faces/face2.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                Tim Cook
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                New product launch
                            </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/regal/regal/images/faces/face3.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                Johnson
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                Upcoming board meeting
                            </p>
                        </div>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown d-flex mr-4 ">
                <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="icon-cog"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Settings</p>
                    <a class="dropdown-item preview-item">
                        <i class="icon-head"></i> Profile
                    </a>
                    <a class="dropdown-item preview-item">
                        <i class="icon-inbox"></i> Logout
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown mr-4 d-lg-flex d-none">
                <a class="nav-link count-indicator d-flex align-items-center justify-content-center" href="#">
                    <i class="icon-grid"></i>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

Project02BurgerMenu/Areas/Admin/Views/AdminLayout/PartialSidebar.cshtml
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

<style>
    .menu-icon {
        display: inline-block;
        font-size: 16px;
        color: #fff;
        margin-right: 8px;
    }
</style>

<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="user-profile">
        <div class="user-image">
            <img src="~/regal/regal/images/Foto KA.jpg">
        </div>
        <div class="user-name">
            Yasin Kereci
        </div>
        <div class="user-designation">
            Software Developer
        </div>
    </div>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Dashboard/Index">
                <i class="fas fa-home menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Admin/Category/CategoryList">
                <i class="fas fa-list menu-icon"></i>
                <span class="menu-title">Categories</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Product/ProductList">
                <i class="fas fa-tag menu-icon"></i>
                <span class="menu-title">Products</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Reservation/ReservationList">
                <i class="fas fa-calendar-alt menu-icon"></i>
                <span class="menu-title">Reservations</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Message/InBox">
                <i class="fas fa-envelope menu-icon"></i>
                <span class="menu-title">Messages</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/About/Index">
                <i class="fas fa-info-circle menu-icon"></i>
                <span class="menu-title">About Us</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Contact/Inbox">
                <i class="fas fa-users menu-icon"></i>
                <span class="menu-title">References</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Chart/ProductStockChart">
                <i class="fas fa-chart-bar menu-icon"></i>
                <span class="menu-title">Charts</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Statistics/Index">
                <i class="fas fa-chart-line menu-icon"></i>
                <span class="menu-title">Statistics</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Admin/CreditCard/Index">
                <i class="fas fa-credit-card menu-icon"></i>
                <span class="menu-title">Credit Card</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Admin/Settings/Index">
                <i class="fas fa-cogs menu-icon"></i>
                <span class="menu-title">Settings</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("LogOut", "Login", new { area = "" })">
                <i class="fas fa-sign-out-alt menu-icon"></i>
                <span class="menu-title">Log Out</span>
            </a>
        </li>
    </ul>
</nav>